// Generated by gencpp from file turtle_control/msgsRequest.msg
// DO NOT EDIT!


#ifndef TURTLE_CONTROL_MESSAGE_MSGSREQUEST_H
#define TURTLE_CONTROL_MESSAGE_MSGSREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace turtle_control
{
template <class ContainerAllocator>
struct msgsRequest_
{
  typedef msgsRequest_<ContainerAllocator> Type;

  msgsRequest_()
    : val(0)
    , val2(0)  {
    }
  msgsRequest_(const ContainerAllocator& _alloc)
    : val(0)
    , val2(0)  {
  (void)_alloc;
    }



   typedef int32_t _val_type;
  _val_type val;

   typedef int32_t _val2_type;
  _val2_type val2;





  typedef boost::shared_ptr< ::turtle_control::msgsRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::turtle_control::msgsRequest_<ContainerAllocator> const> ConstPtr;

}; // struct msgsRequest_

typedef ::turtle_control::msgsRequest_<std::allocator<void> > msgsRequest;

typedef boost::shared_ptr< ::turtle_control::msgsRequest > msgsRequestPtr;
typedef boost::shared_ptr< ::turtle_control::msgsRequest const> msgsRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::turtle_control::msgsRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::turtle_control::msgsRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::turtle_control::msgsRequest_<ContainerAllocator1> & lhs, const ::turtle_control::msgsRequest_<ContainerAllocator2> & rhs)
{
  return lhs.val == rhs.val &&
    lhs.val2 == rhs.val2;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::turtle_control::msgsRequest_<ContainerAllocator1> & lhs, const ::turtle_control::msgsRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace turtle_control

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::turtle_control::msgsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::turtle_control::msgsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::turtle_control::msgsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::turtle_control::msgsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::turtle_control::msgsRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::turtle_control::msgsRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::turtle_control::msgsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "da4c1574a633ac8680814f29d2ae1ca3";
  }

  static const char* value(const ::turtle_control::msgsRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xda4c1574a633ac86ULL;
  static const uint64_t static_value2 = 0x80814f29d2ae1ca3ULL;
};

template<class ContainerAllocator>
struct DataType< ::turtle_control::msgsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "turtle_control/msgsRequest";
  }

  static const char* value(const ::turtle_control::msgsRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::turtle_control::msgsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 val\n"
"int32 val2\n"
;
  }

  static const char* value(const ::turtle_control::msgsRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::turtle_control::msgsRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.val);
      stream.next(m.val2);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct msgsRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::turtle_control::msgsRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::turtle_control::msgsRequest_<ContainerAllocator>& v)
  {
    s << indent << "val: ";
    Printer<int32_t>::stream(s, indent + "  ", v.val);
    s << indent << "val2: ";
    Printer<int32_t>::stream(s, indent + "  ", v.val2);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TURTLE_CONTROL_MESSAGE_MSGSREQUEST_H
