// Generated by gencpp from file turtle_control/msgsResponse.msg
// DO NOT EDIT!


#ifndef TURTLE_CONTROL_MESSAGE_MSGSRESPONSE_H
#define TURTLE_CONTROL_MESSAGE_MSGSRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace turtle_control
{
template <class ContainerAllocator>
struct msgsResponse_
{
  typedef msgsResponse_<ContainerAllocator> Type;

  msgsResponse_()
    : ans(0)
    , ans2(0)  {
    }
  msgsResponse_(const ContainerAllocator& _alloc)
    : ans(0)
    , ans2(0)  {
  (void)_alloc;
    }



   typedef int32_t _ans_type;
  _ans_type ans;

   typedef int32_t _ans2_type;
  _ans2_type ans2;





  typedef boost::shared_ptr< ::turtle_control::msgsResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::turtle_control::msgsResponse_<ContainerAllocator> const> ConstPtr;

}; // struct msgsResponse_

typedef ::turtle_control::msgsResponse_<std::allocator<void> > msgsResponse;

typedef boost::shared_ptr< ::turtle_control::msgsResponse > msgsResponsePtr;
typedef boost::shared_ptr< ::turtle_control::msgsResponse const> msgsResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::turtle_control::msgsResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::turtle_control::msgsResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::turtle_control::msgsResponse_<ContainerAllocator1> & lhs, const ::turtle_control::msgsResponse_<ContainerAllocator2> & rhs)
{
  return lhs.ans == rhs.ans &&
    lhs.ans2 == rhs.ans2;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::turtle_control::msgsResponse_<ContainerAllocator1> & lhs, const ::turtle_control::msgsResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace turtle_control

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::turtle_control::msgsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::turtle_control::msgsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::turtle_control::msgsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::turtle_control::msgsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::turtle_control::msgsResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::turtle_control::msgsResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::turtle_control::msgsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bcef480b088150e87bb027341ad040d4";
  }

  static const char* value(const ::turtle_control::msgsResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xbcef480b088150e8ULL;
  static const uint64_t static_value2 = 0x7bb027341ad040d4ULL;
};

template<class ContainerAllocator>
struct DataType< ::turtle_control::msgsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "turtle_control/msgsResponse";
  }

  static const char* value(const ::turtle_control::msgsResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::turtle_control::msgsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 ans\n"
"int32 ans2\n"
"\n"
"\n"
;
  }

  static const char* value(const ::turtle_control::msgsResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::turtle_control::msgsResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.ans);
      stream.next(m.ans2);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct msgsResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::turtle_control::msgsResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::turtle_control::msgsResponse_<ContainerAllocator>& v)
  {
    s << indent << "ans: ";
    Printer<int32_t>::stream(s, indent + "  ", v.ans);
    s << indent << "ans2: ";
    Printer<int32_t>::stream(s, indent + "  ", v.ans2);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TURTLE_CONTROL_MESSAGE_MSGSRESPONSE_H
