// Generated by gencpp from file turtle_control/msgs.msg
// DO NOT EDIT!


#ifndef TURTLE_CONTROL_MESSAGE_MSGS_H
#define TURTLE_CONTROL_MESSAGE_MSGS_H

#include <ros/service_traits.h>


#include <turtle_control/msgsRequest.h>
#include <turtle_control/msgsResponse.h>


namespace turtle_control
{

struct msgs
{

typedef msgsRequest Request;
typedef msgsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct msgs
} // namespace turtle_control


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::turtle_control::msgs > {
  static const char* value()
  {
    return "0cd72adfcfa06c3a7a00d9b600768e39";
  }

  static const char* value(const ::turtle_control::msgs&) { return value(); }
};

template<>
struct DataType< ::turtle_control::msgs > {
  static const char* value()
  {
    return "turtle_control/msgs";
  }

  static const char* value(const ::turtle_control::msgs&) { return value(); }
};


// service_traits::MD5Sum< ::turtle_control::msgsRequest> should match
// service_traits::MD5Sum< ::turtle_control::msgs >
template<>
struct MD5Sum< ::turtle_control::msgsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::turtle_control::msgs >::value();
  }
  static const char* value(const ::turtle_control::msgsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::turtle_control::msgsRequest> should match
// service_traits::DataType< ::turtle_control::msgs >
template<>
struct DataType< ::turtle_control::msgsRequest>
{
  static const char* value()
  {
    return DataType< ::turtle_control::msgs >::value();
  }
  static const char* value(const ::turtle_control::msgsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::turtle_control::msgsResponse> should match
// service_traits::MD5Sum< ::turtle_control::msgs >
template<>
struct MD5Sum< ::turtle_control::msgsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::turtle_control::msgs >::value();
  }
  static const char* value(const ::turtle_control::msgsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::turtle_control::msgsResponse> should match
// service_traits::DataType< ::turtle_control::msgs >
template<>
struct DataType< ::turtle_control::msgsResponse>
{
  static const char* value()
  {
    return DataType< ::turtle_control::msgs >::value();
  }
  static const char* value(const ::turtle_control::msgsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TURTLE_CONTROL_MESSAGE_MSGS_H
